### ISSUE TITLE
Can't login with onedart cli, stuck on "Verifying Login ..." page

### ISSUE THREAD

**Issue by ahmednfwela** [onepub-dev/onepub#188]
tried to login via website first, and via cli first, but the authentication never gets finished, and I am stuck on this page forever
![image](https://user-images.githubusercontent.com/63286031/203206955-9017a51b-5ced-49db-a941-2804daee8d48.png)
I also tried incognito, etc... but it doesn't work

And using the latest version on github also doesn't work
`dart pub global activate -sgit git@github.com:onepub-dev/onepub.git`

**Comment by ahmednfwela** [comment]
cc @bsutton

**Comment by bsutton** [comment]
Ahmed,
what browser and OS are you using?

**Comment by bsutton** [comment]
Ahmed,
can you try again now.

We think our auth provider breadbutter.io may have been having an issue.

We are investigating further now.

**Comment by ahmednfwela** [comment]
> what browser and OS are you using?

I am using win10 , google chrome

> can you try again now.

still not working

**Comment by bsutton** [comment]
We are waiting on a response from breadbutter.

We also experienced the issue in our dev environment but it was
intermittent and appears to have been resolved.

However we are wondering if the outage is in one (some) of their
distributed end points which have not' recovered as yet.

Can you give it another 30mins and try again.

**Comment by ahmednfwela** [comment]
I still can't login, but I think this is a problem with onepub's handling of the auth itself ?
I tried logging in breadbutter.io directly, and their auth works just fine

**Comment by bsutton** [comment]
what provider are you using?

**Comment by ahmednfwela** [comment]
I tried with google, github, direct email

**Comment by bsutton** [comment]
Are there any errors in your javascript console?

Would you be willing to do a screen share so we can monitor your client and
the server?

**Comment by bsutton** [comment]
Have you successfully registered or are you a new user?

I can't see an Ahmed Fwela in the system.

Being registered or not shouldn't make a difference (as BB works in the
same way both ways) but I'm trying to close any gaps in understanding of
your use case.

**Comment by ahmednfwela** [comment]
1. there are no errors in the javascript console
2. I am a new user
3. Sure we can join a google meet call, please email me at ahmednfwela@bdaya-dev.com

**Comment by bsutton** [comment]
Ahmend,
the problem is on our end :<

It's a permission issue which is denying your registrations.

Give me an hour and we should have it fixed.

Brett

**Comment by bsutton** [comment]
Ahmed,
I believe we have resolved the issue.

Appologies for the inconvenience and thanks for your help in working it
through.

As a thankyou I will organise to upgrade your subscription to Enterprise
(provided you upload at least one package the subscription will be free for
life).

I've got the team doing a review as to why the problem occurred so we can
avoid a repeat.

If there is anything else I can help with please let me know.

On an unrelated note, I'm wondering if I can ask for your opinion.
We are looking to offer a 'secret management' service as part of our core
offering.
Essentially you load environment vars into our UI and then from the cli you
can securely inject them into any apps via:

So in a CI/CD environment

op-secret <scope name> run -- /path/to/your/app

The op-secret command injects all environment variables loaded into the
onepub website associated with the 'scope name'.

Does this sound like a useful service that would make you more likely to
sign up for onepub?


Brett

**Comment by ahmednfwela** [comment]
- Glad to hear that the problem is solved, And I managed to register successfully 
- Also I really appreciate the Enterprise subscription, because I like what your services are offering.
- As for the secret management service, I think it's a really great Idea, since currently we have to distribute the secrets file to our developers via email, and having a CLI tool for that would be a huge improvement.

some ideas for the secret management tool:

1. there should be `per-user` (the developer defines them) and `per-org` secrets (the org owner defines them, and grants access for developers inside the org to use or edit them)
2. ensure secrets are added to `.git-ignore` and `.pubignore` to prevent accidental leaks
3. cli should be able to `sync` secrets , e.g. `op-secret <scope name> upload -- /path/to/your/app`

some ideas for onepub:

1. Ability to rename organizations, change logo, etc ...
2. Once teams are added, package upload permissions should be per-team as well as per-user
